Repository be15-fin-project/be15-fin-DAO-Momentum-FE, pull requests merged in 2025-06, with the labels that each got.

#7 init : 초기 설정에서 삭제되지 않은 import 제거
  src/main.js
Labels: init

#8 [init] 사이드바 및 챗봇 기본 업로드
  index.html
  package-lock.json
  package.json
  public/logo.png
  src/App.vue
  src/assets/css/color-style.css
  src/assets/css/index.css
  src/assets/icons/logo.png
  src/assets/icons/logo_light.png
  src/components/common/Dummy.vue
  src/components/common/chatbot.vue
  src/components/common/sidebar.vue
  src/main.js
Labels: init

#9 Init : 사이드바 및 스크롤 css 수정
  src/assets/css/index.css
  src/components/common/sidebar.vue
Labels: init

#10 init : 초기 설정
  src/features/announcement/api.js
  src/features/announcement/components/Dummy.vue
  src/features/announcement/router.js
  src/features/announcement/views/Dummy.vue
  src/features/approvals/api.js
  src/features/approvals/components/Dummy.vue
  src/features/approvals/router.js
  src/features/approvals/views/Dummy.vue
  src/features/company/api.js
  src/features/company/components/Dummy.vue
  src/features/company/router.js
  src/features/company/views/Dummy.vue
  src/features/employee/api.js
  src/features/employee/components/Dummy.vue
  src/features/employee/router.js
  src/features/employee/views/MainView.vue
  src/features/main/api.js
  src/features/main/components/Dummy.vue
  src/features/main/router.js
  src/features/main/views/MainView.vue
  src/features/mypage/api.js
  src/features/mypage/components/Dummy.vue
  src/features/mypage/router.js
  src/features/mypage/views/Dummy.vue
  src/features/performance/api.js
  src/features/performance/components/Dummy.vue
  src/features/performance/router.js
  src/features/performance/views/Dummy.vue
  src/features/retention-support/api.js
  src/features/retention-support/components/Dummy.vue
  src/features/retention-support/router.js
  src/features/retention-support/views/Dummy.vue
  src/features/settings/api.js
  src/features/settings/components/Dummy.vue
  src/features/settings/router.js
  src/features/settings/views/Dummy.vue
  src/features/works/api.js
  src/features/works/components/Dummy.vue
  src/features/works/router.js
  src/features/works/views/Dummy.vue
  src/router/index.js
Labels: init

#11 init : LayoutDefault 설정
  src/App.vue
  src/components/layout/Dummy.vue
  src/components/layout/LayoutDefault.vue
  src/main.js
  src/router/index.js
Labels: init

#15 feat : 결재 전체 목록 조회
  src/features/approvals/views/ApprovalList.vue
Labels: feat

#24 init : url 경로를 위한 env 파일
  .env
Labels: init

#16 feat: KPI 분석 페이지 하드코딩 구현
  package-lock.json
  package.json
  src/api/axios.js
  src/assets/css/color-style.css
  src/components/common/BaseTable.vue
  src/components/common/Filter.vue
  src/components/common/FormSection.vue
  src/components/common/HeaderWithTabs.vue
  src/components/common/Pagenation.vue
  src/components/common/SideModal.vue
  src/components/common/Sidebar.vue
  src/features/performance/api.js
  src/features/performance/router.js
  src/features/performance/views/KpiDashboardView.vue
  src/main.js
  src/router/index.js
Labels: feat

#77 feat : KPI 분석 조회 기능 구현
  .env
  src/components/common/BaseTable.vue
  src/components/common/Filter.vue
  src/components/common/SideModal.vue
  src/components/common/Sidebar.vue
  src/features/performance/api.js
  src/features/performance/views/KpiDashboardView.vue
Labels: feat

#86 feat: 로그인 페이지 구현, 리프레시, 로그아웃 기능 구현
  package-lock.json
  package.json
  src/api/axios.js
  src/components/common/Sidebar.vue
  src/features/common/api.js
  src/features/common/components/LoginVisualSection.vue
  src/features/common/router.js
  src/features/common/views/LoginView.vue
  src/main.js
  src/router/index.js
  src/stores/auth.js
Labels: feat

#93 init : 사이드바 이동 href에서 router로 변경
  src/components/common/Sidebar.vue
Labels: init

#95 init : 필터 탭 추가, text 저장, 선택 드롭박스 표시
  src/assets/css/color-style.css
  src/components/common/Filter.vue
  src/features/performance/views/MyKpiView.vue
Labels: refactor, init

#99 feat : 자신의 KPi 목록 조회
  src/assets/css/color-style.css
  src/components/common/BaseButton.vue
  src/components/common/FieldRenderer.vue
  src/components/common/SideModal.vue
  src/components/common/Sidebar.vue
  src/features/performance/api.js
  src/features/performance/views/KpiDashboardView.vue
  src/features/performance/views/KpiEmployeeDetailView.vue
  src/features/performance/views/MyKpiView.vue
Labels: feat, refactor, init

#100 feat : 전체 결재 내역 조회 기능
  src/components/common/BaseTable.vue
  src/components/common/NavigationTab.vue
  src/components/common/Sidebar.vue
  src/features/approvals/api.js
  src/features/approvals/components/Dummy.vue
  src/features/approvals/router.js
  src/features/approvals/views/ApprovalList.vue
  src/features/approvals/views/Dummy.vue
  src/features/approvals/views/MyApprovalList.vue
  src/router/index.js
Labels: feat, init
