Repository be15-fin-project/be15-fin-DAO-Momentum-FE, pull requests merged in 2025-07, with the labels that each got.

#103 feat: 출퇴근 목록 조회 기능 구현
  src/components/common/BaseTable.vue
  src/components/common/Filter.vue
  src/components/common/Sidebar.vue
  src/features/works/api.js
  src/features/works/router.js
  src/features/works/views/Dummy.vue
  src/features/works/views/WorkListView.vue
  src/router/index.js
Labels: feat

#105 refactor:로그인 페이지 변경 및 권한에 따른 페이지 접근 여부 추가
  src/assets/css/login.css
  src/features/common/views/LoginView.vue
  src/router/index.js
Labels: feat

#118 feat : 자가 진단 목록 조회 및 상세 조회 구현, 엑셀 다운로드 구현
  src/features/performance/api.js
  src/features/performance/router.js
  src/features/performance/views/EvaluationSelfView.vue
Labels: feat

#121 feat: 결재 알림 기능 구현
  .env
  package-lock.json
  package.json
  src/App.vue
  src/api/attachAuthInterceptor.js
  src/api/axios.js
  src/api/notificationApi.js
  src/components/common/AlertPanel.vue
  src/components/common/Sidebar.vue
  src/main.js
  src/stores/auth.js
  src/stores/notification.js
Labels: feat

#122 feat : 평가 회차 관리 페이지 구현
  package-lock.json
  package.json
  src/components/common/FieldRenderer.vue
  src/components/common/SideModal.vue
  src/components/common/Sidebar.vue
  src/components/common/SliderGroup.vue
  src/features/performance/api.js
  src/features/performance/components/Dummy.vue
  src/features/performance/router.js
  src/features/performance/views/EvaluationOrgView.vue
  src/features/performance/views/EvaluationPeerView.vue
  src/features/performance/views/EvaluationRoundView.vue
  src/features/performance/views/EvaluationSelfView.vue
  src/features/performance/views/KpiDashboardView.vue
  src/features/performance/views/KpiEmployeeDetailView.vue
  src/features/performance/views/KpiEmployeeListView.vue
  src/features/performance/views/KpiRequestsView.vue
  src/features/performance/views/MyKpiView.vue
  src/features/performance/views/SubmitEvaluationTasks.vue
Labels: feat

#114 feat: 회사 정보 조회 페이지 구현
  src/features/company/api.js
  src/features/company/router.js
  src/features/company/views/CompanyInfoView.vue
  src/features/company/views/Dummy.vue
  src/router/index.js
Labels: feat

#123 feat: 계약서 목록 조회, 다운로드 기능 구현
  src/components/common/Filter.vue
  src/components/common/Sidebar.vue
  src/features/employee/api.js
  src/features/employee/router.js
  src/features/employee/views/ContractListView.vue
Labels: feat

#127 feat: 회사 조직도 조회 페이지 구현
  package-lock.json
  package.json
  src/features/company/api.js
  src/features/company/router.js
  src/features/company/views/OrgChartView.vue
Labels: feat

#128 feat: 인사 발령 내역 조회 및 등록 기능 구현
  src/components/common/Sidebar.vue
  src/features/employee/api.js
  src/features/employee/router.js
  src/features/employee/views/AppointListView.vue
Labels: feat

#131 feat: 평가 기간에 따른 사이드바 메뉴 조회, 인사 평가내역 조회
  src/components/common/FieldRenderer.vue
  src/components/common/SideModal.vue
  src/components/common/Sidebar.vue
  src/components/common/form/FormSection.vue
  src/components/common/form/LikertScale.vue
  src/components/common/form/RadarChart.vue
  src/components/common/form/ScoreBarChart.vue
  src/components/common/form/SliderGroup.vue
  src/features/performance/api.js
  src/features/performance/router.js
  src/features/performance/views/EvaluationOrgView.vue
  src/features/performance/views/EvaluationPeerView.vue
  src/features/performance/views/EvaluationRoundView.vue
  src/features/performance/views/EvaluationSelfView.vue
  src/features/performance/views/KpiDashboardView.vue
  src/features/performance/views/KpiEmployeeDetailView.vue
  src/features/performance/views/KpiEmployeeListView.vue
  src/features/performance/views/KpiRequestsView.vue
  src/features/performance/views/MyHrEvaluationView.vue
  src/features/performance/views/MyKpiView.vue
  src/features/performance/views/SubmitEvaluationTasks.vue
Labels: feat

#133 feat : 이의 제기 내역 조회 기능 구현
  src/components/common/Sidebar.vue
  src/features/performance/api.js
  src/features/performance/router.js
  src/features/performance/views/EvaluationOrgView.vue
  src/features/performance/views/EvaluationPeerView.vue
  src/features/performance/views/EvaluationSelfView.vue
  src/features/performance/views/MyHrEvaluationView.vue
  src/features/performance/views/MyHrObjectionListView.vue
Labels: feat

#142 refactor: 회사 조직도 페이지 일부 컴포넌트화
  src/features/company/components/Dummy.vue
  src/features/company/components/MemberCard.vue
  src/features/company/components/MemberList.vue
  src/features/company/components/OrgTree.vue
  src/features/company/views/OrgChartView.vue
Labels: refactor

#143 refactor : 잘못 작성된 주석과 import 수정
  src/features/approvals/components/SentApproval.vue
  src/features/approvals/components/approveType/CancelForm.vue
Labels: refactor

#147 feat : 근속 전망 회차 등록 및 목록 조회 구현
  src/features/performance/views/EvaluationRoundView.vue
  src/features/performance/views/MyKpiView.vue
  src/features/retention-support/api.js
  src/features/retention-support/router.js
  src/features/retention-support/views/ProspectEmployeeListView.vue
  src/features/retention-support/views/RetentionRoundView.vue
Labels: feat

#152 [fix] 사이드바 수정
  src/components/common/Sidebar.vue
Labels: fix

#153 init : 토스트 알림 컴포넌트 추가 및 콘솔 알림 수정
  package.json
  src/components/common/DeleteConfirmToast.vue
  src/components/common/form/FieldRenderer.vue
  src/features/performance/views/EvaluationOrgView.vue
  src/features/performance/views/EvaluationPeerView.vue
  src/features/performance/views/EvaluationRoundView.vue
  src/features/performance/views/EvaluationSelfView.vue
  src/features/performance/views/HrObjectionListView.vue
  src/features/performance/views/HrObjectionRequestView.vue
  src/features/performance/views/KpiDashboardView.vue
  src/features/performance/views/KpiEmployeeDetailView.vue
  src/features/performance/views/KpiEmployeeListView.vue
  src/features/performance/views/KpiRequestsView.vue
  src/features/performance/views/MyHrEvaluationView.vue
  src/features/performance/views/MyKpiView.vue
  src/features/performance/views/SubmitEvaluationTasks.vue
  src/features/retention-support/views/ContactRecordView.vue
  src/features/retention-support/views/MyRetentionContactView.vue
  src/features/retention-support/views/ProspectDashboardView.vue
  src/features/retention-support/views/ProspectEmployeeListView.vue
  src/features/retention-support/views/RetentionRoundView.vue
Labels: init

#150 refactor : 첨부파일 조회 추가 및 css 수정
  src/components/common/BaseTable.vue
  src/features/approvals/components/ApprovalSideSection.vue
  src/features/approvals/components/FormSection.vue
  src/features/approvals/components/approveType/BusinessTripForm.vue
  src/features/approvals/components/approveType/CancelForm.vue
  src/features/approvals/components/approveType/OvertimeForm.vue
  src/features/approvals/components/approveType/ProposalForm.vue
  src/features/approvals/components/approveType/ReceiptForm.vue
  src/features/approvals/components/approveType/RemoteWorkForm.vue
  src/features/approvals/components/approveType/VacationForm.vue
  src/features/approvals/components/approveType/WorkCorrectionForm.vue
  src/features/approvals/views/ApprovalDetail.vue
  src/features/approvals/views/ApprovalList.vue
Labels: refactor, init, style

#154 refactor: 목록 조회 페이지 부서 필터 수정
  src/components/common/Pagination.vue
  src/components/common/Sidebar.vue
  src/features/employee/views/AppointListView.vue
  src/features/employee/views/ContractListView.vue
  src/features/employee/views/EmployeeListView.vue
  src/features/works/composable/useAttendance.js
  src/features/works/views/WorkListView.vue
Labels: fix, refactor

#155 feat : 결재 문서 승인, 반려 기능 구현
  src/features/approvals/api.js
  src/features/approvals/components/FormSection.vue
  src/features/approvals/components/approveType/CancelForm.vue
  src/features/approvals/router.js
  src/features/approvals/views/ApproveDetailActionView.vue
Labels: feat, refactor, style

#166 refactor : 근태 모달 및 캘린더 근태 조회 모달 수정
  src/components/common/CommonModal.vue
  src/components/common/Sidebar.vue
  src/features/works/components/AttendanceCard.vue
  src/features/works/components/AttendanceModal.vue
  src/features/works/components/CalendarAttendanceModal.vue
Labels: refactor

#164 feat: 본인 계약서 조회, 관리자 계약서 조회, 등록, 삭제 기능 구현
  src/components/common/BaseTable.vue
  src/components/common/SideModal.vue
  src/components/common/Sidebar.vue
  src/components/common/form/FieldRenderer.vue
  src/features/employee/api.js
  src/features/employee/views/ContractListView.vue
  src/features/mypage/router.js
  src/features/mypage/views/MyContractsView.vue
Labels: feat

#168 feat: 사원 등록 시 권한 설정 구현, 발령 등록 구현
  src/components/common/BaseButton.vue
  src/components/common/TreeNode.vue
  src/components/common/form/FieldRenderer.vue
  src/features/employee/views/AppointListView.vue
  src/features/employee/views/EmployeeListView.vue
Labels: feat

#171 부서 설정 페이지 구현
  src/components/common/form/DeptList.vue
  src/components/common/form/FieldRenderer.vue
  src/features/company/components/DepartmentInfoCard.vue
  src/features/company/views/OrgChartView.vue
  src/features/settings/api.js
  src/features/settings/router.js
  src/features/settings/views/CompanyForm.vue
  src/features/settings/views/DepartmentForm.vue
  src/features/settings/views/SettingView.vue
Labels: feat

#173 feat: 목록 조회 페이지 수정 (FileRenderer fix 포함)
  src/components/common/BaseTable.vue
  src/components/common/form/FieldRenderer.vue
  src/features/employee/views/AppointListView.vue
  src/features/employee/views/ContractListView.vue
  src/features/employee/views/EmployeeListView.vue
  src/features/mypage/views/MyContractsView.vue
  src/features/works/views/WorkListView.vue
Labels: feat, fix

#175 feat : 결재 문서 작성 기능
  src/features/approvals/api.js
  src/features/approvals/components/ApprovalSideSection.vue
  src/features/approvals/components/EmployeeModal.vue
  src/features/approvals/components/FormSection.vue
  src/features/approvals/components/WriteFormSection.vue
  src/features/approvals/components/approveType/BusinessTripForm.vue
  src/features/approvals/components/approveType/OvertimeForm.vue
  src/features/approvals/components/approveType/ProposalForm.vue
  src/features/approvals/components/approveType/ReceiptForm.vue
  src/features/approvals/components/approveType/VacationForm.vue
  src/features/approvals/router.js
  src/features/approvals/views/ApprovalList.vue
  src/features/approvals/views/ApproveEditCreateView.vue
Labels: feat

#177 refactor : KPI 상세 조회 수정 및 근속 전망 목록 정보 수정
  src/features/performance/views/KpiDashboardView.vue
  src/features/performance/views/KpiEmployeeDetailView.vue
  src/features/retention-support/components/DeptStabilityBar.vue
  src/features/retention-support/components/StabilityDonut.vue
  src/features/retention-support/views/ProspectEmployeeListView.vue
  src/features/retention-support/views/RetentionRoundView.vue
Labels: refactor

#180 [feat #107] 직위 정보 설정 페이지 구현
  src/features/settings/api.js
  src/features/settings/router.js
  src/features/settings/views/CompanyForm.vue
  src/features/settings/views/DepartmentForm.vue
  src/features/settings/views/PositionForm.vue
  src/features/settings/views/SettingView.vue
Labels: feat

#183 refactor: 발령 등록 UX/UI 개선
  src/features/employee/views/AppointListView.vue
Labels: fix, refactor

#184 feat : 결재 문서 작성 기능 구현
  src/features/approvals/api.js
  src/features/approvals/components/ApprovalSideSection.vue
  src/features/approvals/components/EmployeeModal.vue
  src/features/approvals/components/ReceivedApproval.vue
  src/features/approvals/components/SentApproval.vue
  src/features/approvals/components/WriteFormSection.vue
  src/features/approvals/components/approveType/BusinessTripForm.vue
  src/features/approvals/components/approveType/OvertimeForm.vue
  src/features/approvals/components/approveType/ProposalForm.vue
  src/features/approvals/components/approveType/ReceiptForm.vue
  src/features/approvals/components/approveType/RemoteWorkForm.vue
  src/features/approvals/components/approveType/VacationForm.vue
  src/features/approvals/components/approveType/WorkCorrectionForm.vue
  src/features/approvals/views/ApproveDetailActionView.vue
  src/features/approvals/views/ApproveEditCreateView.vue
  src/features/approvals/views/MyApprovalList.vue
Labels: feat, fix, refactor

#186 refactor: 사원 등록 UX/UI 개선
  src/components/common/form/FieldRenderer.vue
  src/features/employee/views/EmployeeListView.vue
Labels: refactor

#187 refactor : 안전성 비율 API 수정에 따른 페이지 수정
  src/components/common/form/SliderGroup.vue
  src/features/performance/views/EvaluationRoundView.vue
  src/features/performance/views/SubmitEvaluationTasks.vue
  src/features/retention-support/components/StabilityDonut.vue
Labels: refactor

#188 fix : 결재 문서 관련 오류 및 디자인 수정
  src/components/common/Sidebar.vue
  src/features/approvals/components/ReceivedApproval.vue
  src/features/approvals/components/SentApproval.vue
  src/features/approvals/components/approveType/BusinessTripForm.vue
  src/features/approvals/components/approveType/ProposalForm.vue
  src/features/approvals/components/approveType/ReceiptForm.vue
  src/features/approvals/components/approveType/VacationForm.vue
  src/features/approvals/views/ApprovalList.vue
  src/features/approvals/views/ApproveDetailActionView.vue
  src/features/approvals/views/ApproveEditCreateView.vue
Labels: fix, refactor, style

#189 refactor : 전반적인 css 수정
  src/assets/css/color-style.css
  src/components/common/form/FieldRenderer.vue
  src/components/common/form/FormNotice.vue
  src/components/common/form/ProgressTimeline.vue
  src/components/common/form/RetentionScoreCard.vue
  src/features/performance/views/SubmitEvaluationTasks.vue
  src/features/retention-support/components/StabilityDonut.vue
  src/features/retention-support/views/ProspectEmployeeListView.vue
Labels: refactor

#191 refactor: 사이드바 수정
  src/components/common/Sidebar.vue
Labels: refactor

#185 [feat #109] 권한 정보 설정 페이지 구현
  src/features/company/components/MemberCard.vue
  src/features/settings/api.js
  src/features/settings/components/RoleOptionCard.vue
  src/features/settings/router.js
  src/features/settings/views/RoleForm.vue
  src/features/settings/views/SettingView.vue
Labels: feat

#194 refactor: 사원 CSV 일괄 등록 페이지 수정
  src/features/employee/views/CSVUploadView.vue
  src/features/employee/views/EmployeeListView.vue
Labels: refactor

#195 refactor : 필터 및 모달 일부 수정
  src/features/performance/views/EvaluationOrgView.vue
  src/features/performance/views/HrObjectionListView.vue
  src/features/performance/views/HrObjectionRequestView.vue
  src/features/performance/views/KpiEmployeeListView.vue
  src/features/performance/views/MyHrEvaluationView.vue
  src/features/performance/views/MyKpiView.vue
Labels: refactor

#193 feat: 휴일 관리 페이지 구현
  src/components/common/Filter.vue
  src/components/common/Sidebar.vue
  src/features/settings/api.js
  src/features/settings/router.js
  src/features/settings/views/HoolidayForm.vue
  src/features/settings/views/SettingView.vue
Labels: feat

#200 feat : 결재 문서 회수 기능
  src/features/approvals/api.js
  src/features/approvals/components/FormSection.vue
  src/features/approvals/components/ReceivedApproval.vue
  src/features/approvals/views/ApproveDetailActionView.vue
  src/features/approvals/views/ApproveEditCreateView.vue
Labels: feat, refactor, style

#196 feat : 근속 전망 상세 조회에서 면담 요청 진행
  src/components/common/SideModal.vue
  src/components/common/form/MemberPickerField.vue
  src/features/retention-support/api.js
  src/features/retention-support/components/OrgTree.vue
  src/features/retention-support/views/ContactRecordView.vue
  src/features/retention-support/views/ProspectEmployeeListView.vue
Labels: feat

#202 fix : 취소 결재 추가 및 수정
  src/features/approvals/components/FormSection.vue
  src/features/approvals/components/approveType/CancelForm.vue
  src/features/approvals/components/approveType/WorkCorrectionForm.vue
  src/features/approvals/views/ApproveDetailActionView.vue
  src/features/approvals/views/ApproveEditCreateView.vue
Labels: feat, fix, refactor, style

#203 fix: 내 계약서 조회 페이지 수정
  src/components/common/Sidebar.vue
  src/features/mypage/views/MyContractsView.vue
Labels: fix

#206 refactor: 사이드바 수정
  src/components/common/Sidebar.vue
Labels: refactor

#208 style: 내 정보 조회 페이지 스타일 수정
  src/features/mypage/views/EmployeeProfileView.vue
Labels: feat

#209 [style] 사원 프로필 조회 css 수정
  src/features/employee/views/AdminEmployeeProfileView.vue
Labels: style

#210 style: 회사 정보, 조직도 css 수정
  src/features/company/components/DepartmentInfoCard.vue
  src/features/company/views/CompanyInfoView.vue
  src/features/company/views/OrgChartView.vue
Labels: style

#214 refactor : 전체적인 크리 80% 축소
  src/assets/css/index.css
  src/assets/css/login.css
  src/components/common/Sidebar.vue
  src/components/layout/LayoutDefault.vue
Labels: refactor

#216 refactor : 사이드 모달 및 페이지네이션 css 수정
  src/components/common/Pagination.vue
  src/components/common/SideModal.vue
Labels: refactor

#215 [fix] 인사 정보 수정 기능
  src/features/employee/components/profile/HistoryInfoEditable.vue
  src/features/employee/views/AdminEmployeeProfileView.vue
Labels: fix

#219 refactor KPI 진행 현황 통계 수정 및 KPI 상태 조건 수정
  src/components/common/CommonModal.vue
  src/features/performance/components/DonutChart.vue
  src/features/performance/components/LineChart.vue
  src/features/performance/views/KpiDashboardView.vue
  src/features/performance/views/MyKpiView.vue
Labels: refactor

#221 style: 설정 페이지 전반적인 css 수정
  src/features/settings/components/CompanyBanner.vue
  src/features/settings/components/RoleOptionCard.vue
  src/features/settings/views/CompanyForm.vue
  src/features/settings/views/DepartmentForm.vue
  src/features/settings/views/RoleForm.vue
  src/features/settings/views/SettingView.vue
Labels: style

#220 [fix] 근태 목록 조회 탭 수정
  src/features/works/views/WorkListView.vue
Labels: fix

#222 style: 부서 삭제 모달 변경
  src/features/settings/views/DepartmentForm.vue
  src/features/settings/views/HoolidayForm.vue
Labels: style

#213 feat: 알림 패널에서 보이는 title 추가 - 결재 반려, 결재 완료, 평가 시작, 평가 종료
  src/components/common/AlertPanel.vue
  src/components/common/Chatbot.vue
Labels: feat

#224 [style] 공지사항 알림 수정
  src/features/announcement/views/AnnouncementCreateView.vue
  src/features/announcement/views/AnnouncementDetailView.vue
  src/features/announcement/views/AnnouncementEditView.vue
Labels: style

#225 fix: 권한 수정 동작 수정
  src/features/settings/views/RoleForm.vue
Labels: fix

#226 [refactor #21] 인사 발령 내역 조회 페이지 수정
  src/features/employee/views/AppointListView.vue
Labels: refactor

#229 [refactor] 퇴근 등록 기능 수정
  src/features/works/composable/useAttendance.js
Labels: refactor

#231 refactor : css 수정 및 근속 전망 지수 툴팁 수정
  src/components/common/form/FieldRenderer.vue
  src/components/common/form/RadarChart.vue
  src/components/common/form/RetentionScoreCard.vue
  src/features/retention-support/components/MetricCard.vue
  src/features/retention-support/views/ProspectDashboardView.vue
  src/features/retention-support/views/ProspectEmployeeListView.vue
Labels: refactor

#233 [style] 회사 정보 페이지 스타일 수정
  src/components/common/HeaderWithTabs.vue
  src/components/common/NavigationTab.vue
  src/features/company/views/CompanyInfoView.vue
Labels: style

#235 refactor 사이드바 정보 수정 - 회사 정보 대신 프로필 정보 및 알림 모달 css 수정
  src/components/common/AlertPanel.vue
  src/components/common/Filter.vue
  src/components/common/Sidebar.vue
Labels: refactor

#239 refactor : css 전반적 수정 및 안내 페이지 추가
  src/features/common/components/FeatureCard.vue
  src/features/common/router.js
  src/features/common/views/FeatureCardView.vue
  src/features/main/api.js
  src/features/main/components/Dummy.vue
  src/features/main/router.js
  src/features/main/views/MainView.vue
  src/features/retention-support/components/StabilityDonut.vue
Labels: refactor

#240 refactor: 토스트 알림 수정
  src/components/common/DeleteConfirmToast.vue
  src/components/common/Sidebar.vue
  src/components/common/form/FieldRenderer.vue
  src/features/employee/components/profile/HistoryInfoEditable.vue
  src/features/employee/views/AdminEmployeeProfileView.vue
  src/features/employee/views/AppointListView.vue
  src/features/employee/views/CSVUploadView.vue
  src/features/employee/views/ContractListView.vue
  src/features/employee/views/EmployeeListView.vue
  src/features/mypage/views/MyContractsView.vue
  src/features/works/views/WorkListView.vue
Labels: refactor

#242 fix: css 클래스명 변경 및 버튼 클릭 이벤트 위치 변경
  src/features/company/components/DepartmentInfoCard.vue
  src/features/company/views/OrgChartView.vue
Labels: fix

#243 fix: 비밀번호 재설정 페이지 기능 수정
  src/features/common/api.js
  src/features/common/components/PasswordResetForm.vue
  src/features/common/views/ResetPasswordView.vue
Labels: fix

#244 style: 사이드바 출퇴근 버튼 수정
  src/components/common/Sidebar.vue
  src/features/works/composable/useAttendance.js
Labels: style

#247 style: 출퇴근 버튼 수정
  src/features/works/composable/useAttendance.js
Labels: style

#248 refactor: 용어 통일
  src/components/common/Chatbot.vue
  src/features/employee/components/profile/BasicInfo.vue
  src/features/employee/components/profile/HistoryInfo.vue
  src/features/employee/components/profile/HistoryInfoEditable.vue
  src/features/employee/views/AdminEmployeeProfileView.vue
  src/features/mypage/components/profile/BasicInfo.vue
  src/features/mypage/components/profile/HistoryInfo.vue
  src/features/mypage/views/EmployeeProfileView.vue
Labels: refactor

#249 refactor: 권한명 수정
  src/components/common/Chatbot.vue
  src/features/employee/views/EmployeeListView.vue
  src/features/settings/views/RoleForm.vue
Labels: refactor

#251 [style] 인사 정보 수정 페이지, 알림 영역(NoticeItem, PositionForm) 스타일 수정
  src/features/employee/components/NoticeItem.vue
  src/features/employee/components/profile/HistoryInfoEditable.vue
  src/features/settings/views/PositionForm.vue
Labels: style

#253 fix: 오타 수정,용어 통일 및 애니메이션 추가
  src/features/settings/views/CompanyForm.vue
  src/features/settings/views/HoolidayForm.vue
  src/features/settings/views/PositionForm.vue
Labels: fix

#255 refactor: 불필요한 로그 삭제
  src/components/common/SideModal.vue
  src/components/common/form/FieldRenderer.vue
  src/features/works/composable/useAttendance.js
Labels: refactor

#256 fix: 설정 페이지 불필요 로그 제거
  src/features/settings/views/RoleForm.vue
Labels: fix

#257 [refactor] 발령 내역 조회 필터 조건 추가
  src/features/employee/views/AppointListView.vue
  src/features/employee/views/MainView.vue
Labels: refactor

#259 fix: intro 페이지 권한 삭제
  src/router/index.js
Labels: fix

#254 refactor: 챗봇 메시지 '\n' 반영되도록 css 수정
  src/components/common/Chatbot.vue
Labels: refactor

#261 docs: github actions deploy.yml 작성
  .github/workflows/deploy.yml
Labels: docs

#263 docs: github actions deploy 수정
  .github/workflows/deploy.yml
Labels: docs

#264 docs: github actions deploy,yml 수정
  .github/workflows/deploy.yml
Labels: docs

#265 fix: 배포 환경에서 헤더 생성되지 않는 문제 수정
  src/features/employee/views/AdminEmployeeProfileView.vue
Labels: fix

#266 refactor : 조회 오류 수정 및 CSS 수정, 로그 삭제
  src/features/common/views/IntroView.vue
  src/features/performance/views/HrObjectionRequestView.vue
  src/features/performance/views/KpiDashboardView.vue
  src/features/performance/views/KpiEmployeeDetailView.vue
  src/features/performance/views/KpiEmployeeListView.vue
  src/features/performance/views/KpiRequestsView.vue
  src/features/performance/views/MyKpiView.vue
  src/features/retention-support/components/MetricCard.vue
  src/features/retention-support/views/ProspectEmployeeListView.vue
Labels: refactor

#268 fix: console.log 제거
  src/features/common/views/LoginView.vue
  src/features/company/views/OrgChartView.vue
  src/stores/auth.js
Labels: refactor

#269 refactor : 소개 페이지 로그인 버튼 CSS 확정
  src/features/common/views/IntroView.vue
  src/features/retention-support/components/MetricCard.vue
  src/features/retention-support/views/RetentionRoundView.vue
Labels: refactor

#270 fix: 로그인 기본값 제거
  src/features/common/views/LoginView.vue
Labels: fix

#271 refactor : 드래그, 소개, 사이드바 스타일 수정
  src/assets/css/index.css
  src/components/common/SideModal.vue
  src/features/common/views/IntroView.vue
  src/features/performance/views/KpiEmployeeDetailView.vue
  src/features/performance/views/KpiRequestsView.vue
  src/features/performance/views/MyKpiView.vue
Labels: refactor

#273 refactor : KPI 승인,반려,취소 상태일 경우 처리 사유 수정 불가능, 인사 평가 조회 사원1번은 불가능하게 수정
  src/components/common/Sidebar.vue
  src/features/performance/views/KpiRequestsView.vue
Labels: refactor

#274 refactor: 프론트엔드 검증 로직 추가
  src/features/employee/components/UploadCard.vue
  src/features/employee/components/profile/HistoryInfoEditable.vue
  src/features/employee/views/AdminEmployeeProfileView.vue
  src/features/employee/views/AppointListView.vue
  src/features/employee/views/ContractListView.vue
  src/features/employee/views/EmployeeListView.vue
  src/util/toastError.js
Labels: refactor

#275 refactor: 사이드바 알림 아이콘 위치 수정
  src/components/common/Sidebar.vue
Labels: refactor

#277 [fix] 알림 아이콘 collapsed 상태면 렌더링 안하도록 수정
  src/components/common/Sidebar.vue
Labels: fix

#276 fix: 로그인 폼 수정
  src/features/common/views/LoginView.vue
Labels: fix

#280 refactor: console 출력 제거
  src/components/common/SideModal.vue
  src/components/common/Sidebar.vue
  src/components/common/form/MemberPickerField.vue
  src/features/mypage/components/VacationInfoCard.vue
  src/features/mypage/views/EmployeeProfileView.vue
Labels: refactor

#281 fix: console 메세지 처리 변경
  src/features/common/components/PasswordResetForm.vue
  src/features/company/views/CompanyInfoView.vue
  src/features/company/views/OrgChartView.vue
Labels: fix

#282 refactor: 콘솔 에러, 로그 출력 -> toastification으로 대체
  src/components/common/AlertPanel.vue
  src/features/announcement/views/AnnouncementCreateView.vue
  src/features/announcement/views/AnnouncementDetailView.vue
  src/features/announcement/views/AnnouncementEditView.vue
  src/features/announcement/views/AnnouncementListView.vue
  src/stores/notification.js
Labels: refactor

#284 refactor : 권한별 면담 내역 및 면담 요청 내역 조회 변경
  src/components/common/Sidebar.vue
  src/features/retention-support/views/ContactRecordView.vue
  src/features/retention-support/views/MyRetentionContactView.vue
Labels: refactor

#287 PR #284 #286 배포
  src/components/common/Chatbot.vue
  src/components/common/Sidebar.vue
  src/features/retention-support/views/ContactRecordView.vue
  src/features/retention-support/views/MyRetentionContactView.vue
Labels: Pull Request

#291 fix: 직위 입력 폼 변경
  src/features/settings/views/PositionForm.vue
Labels: fix
